[project]
name = "ComfyUI-AutoMask"
description = "Automatic mask refinement and histogram-based multi-threshold nodes for ComfyUI by easygoing0114"
version = "0.2.1"
license = { text = "MIT" }

[project.urls]
Repository = "https://github.com/easygoing0114/ComfyUI-AutoMask"
Documentation = "https://www.ai-image-journey.com/2026/08/birefnet-depthanythingv3-sam31-lama.html"

[tool.comfy]
PublisherId = "easygoing0114"
DisplayName = "Auto Mask"
Icon = "https://raw.githubusercontent.com/easygoing0114/ComfyUI-AutoMask/main/images/ComfyUI-AutoMask_icon_image.png"
Banner = "https://raw.githubusercontent.com/easygoing0114/ComfyUI-AutoMask/main/images/ComfyUI-AutoMask_banner_image.png"
